### ISSUE TITLE
Info should be an image

### ISSUE THREAD

**Issue by infi** [JDiscordBots/NightDream#3]
![dt-info / @Unfi / <Description of Daydream instance>](https://user-images.githubusercontent.com/45950794/62824631-426bca80-bba1-11e9-983e-eeda9bdf41e2.png)
See [imageProcessing.js](https://gitlab.com/botstudio/daydream/blob/master/imageProcessing.js)

**Comment by danthe1st** [comment]
This issue is against the contributing guidelines.
Although, it has a good point.
So, it won't be marked as invalid.

**Comment by danthe1st** [comment]
added in commits 6a56df29f2fa8a888134669362ce9c890b699055 and 503a85dd4e561ffa9e77185ef3754b2bcdabddb1
